/**
 * VENTURR VALIDT - Report Engine v1.0
 * Produces two outputs:
 * 1. VALIDT Verification Report (client-friendly)
 * 2. VALIDT Evidence / Court Report (defensible, clause-driven)
 * 
 * Each section includes:
 * - Findings table
 * - Evidence list (citations)
 * - Assumptions
 * - Confidence score
 * - "What evidence is still required" checklist
 */

import { Citation, Finding, AuditLogEntry, containsBlockedLanguage } from '../shared/citations';
import { citeOrBlockMiddleware, ConflictingSource } from './citeOrBlockMiddleware';
import { getAuditTrail } from './auditTrail';
import { COMPLIANCE_RULES, getRuleById } from './complianceKnowledgeBase';

export interface ReportSection {
  id: string;
  title: string;
  category: "pricing" | "materials" | "compliance" | "warranty" | "summary";
  findings: Finding[];
  score: number;
  confidence: "high" | "medium" | "low";
  assumptions: string[];
  evidenceRequired: string[];
  citations: Citation[];
}

export interface ClientReport {
  reportId: string;
  reportType: "client" | "court";
  generatedAt: string;
  quoteId: number;
  projectAddress?: string;
  contractorName?: string;
  
  // Summary
  overallScore: number;
  overallStatus: "green" | "amber" | "red";
  overallConfidence: "high" | "medium" | "low";
  executiveSummary: string;
  
  // Sections
  sections: ReportSection[];
  
  // Recommendations
  recommendations: Array<{
    priority: "high" | "medium" | "low";
    title: string;
    description: string;
    relatedFindings: string[];
  }>;
  
  // Warnings & Disclaimers
  warnings: string[];
  disclaimer: string;
  
  // Metadata
  analysisVersion: string;
  standardsReferenced: string[];
}

export interface CourtReport extends Omit<ClientReport, 'reportType'> {
  reportType: "court";
  
  // Additional court-specific sections
  auditTrail: AuditLogEntry[];
  conflictingSources: ConflictingSource[];
  
  // Detailed evidence chain
  evidenceChain: Array<{
    step: number;
    action: string;
    timestamp: string;
    input: string;
    output: string;
    confidence: string;
  }>;
  
  // Methodology statement
  methodology: {
    extractionMethod: string;
    analysisModel: string;
    standardsVersion: string;
    validationSteps: string[];
  };
  
  // Legal notices
  legalNotices: string[];
  expertWitnessStatement: string;
}

/**
 * Standard disclaimer text
 */
const STANDARD_DISCLAIMER = `
IMPORTANT DISCLAIMER

This report has been generated by VENTURR VALIDT, an AI-assisted quote analysis system. 
The findings presented are assessments based on the evidence provided and referenced standards, 
NOT attestations, endorsements, or assurances.

This report:
- Is NOT a substitute for professional advice from licensed builders, engineers, or legal professionals
- Does NOT verify or attest to compliance with any building code or standard
- Does NOT assure the accuracy of contractor quotes or pricing
- Should be used as ONE input in your decision-making process

All findings are assessed against referenced standards and evidence provided. Users should:
1. Verify all critical information independently
2. Consult licensed professionals for compliance determinations
3. Obtain multiple quotes for comparison
4. Review contractor licenses and insurance independently

VENTURR VALIDT and its operators accept no liability for decisions made based on this report.
`.trim();

/**
 * Expert witness statement for court reports
 */
const EXPERT_WITNESS_STATEMENT = `
STATEMENT OF METHODOLOGY AND LIMITATIONS

This report was generated using automated analysis of the provided quote document against 
referenced Australian building standards and codes. The analysis methodology includes:

1. Document Extraction: Text was extracted from the provided document using PDF parsing 
   and/or Optical Character Recognition (OCR) technology.

2. Standards Reference: Findings reference specific clauses from authoritative sources 
   including the National Construction Code (NCC), HB 39, SafeWork NSW Codes of Practice, 
   and relevant Australian Standards.

3. AI-Assisted Analysis: Natural language processing was used to identify and categorize 
   quote elements against known compliance requirements.

4. Citation Verification: Every finding in this report is linked to at least one 
   authoritative source. Findings without verifiable citations are marked as 
   "insufficient evidence."

LIMITATIONS:
- This analysis is based solely on the document provided and cannot verify physical conditions
- OCR extraction may introduce errors in text interpretation
- Standards interpretations are general and may not account for site-specific conditions
- This report does not replace inspection by qualified professionals

The confidence levels assigned to findings reflect the quality of evidence available, 
not the certainty of compliance or non-compliance.
`.trim();

/**
 * Generate executive summary based on findings
 */
function generateExecutiveSummary(
  sections: ReportSection[],
  overallScore: number,
  overallConfidence: "high" | "medium" | "low"
): string {
  const highPriorityIssues = sections.flatMap(s => 
    s.findings.filter(f => f.status === "flagged")
  ).length;
  
  const insufficientEvidence = sections.flatMap(s =>
    s.findings.filter(f => f.status === "insufficient-evidence")
  ).length;
  
  let summary = `This quote has been assessed against referenced Australian building standards and industry benchmarks. `;
  
  if (overallScore >= 85) {
    summary += `The overall assessment score of ${overallScore}/100 indicates the quote appears to align well with typical market expectations and referenced standards. `;
  } else if (overallScore >= 70) {
    summary += `The overall assessment score of ${overallScore}/100 indicates some areas may warrant further review or clarification. `;
  } else {
    summary += `The overall assessment score of ${overallScore}/100 indicates several areas require attention before proceeding. `;
  }
  
  if (highPriorityIssues > 0) {
    summary += `${highPriorityIssues} item(s) have been flagged for review. `;
  }
  
  if (insufficientEvidence > 0) {
    summary += `${insufficientEvidence} item(s) could not be fully assessed due to insufficient evidence in the provided document. `;
  }
  
  if (overallConfidence === "low") {
    summary += `Note: The overall confidence of this assessment is LOW due to limitations in the extracted document content. Results should be interpreted with caution.`;
  } else if (overallConfidence === "medium") {
    summary += `The assessment confidence is MEDIUM. Some findings may benefit from additional documentation.`;
  }
  
  return summary;
}

/**
 * Build evidence chain from audit trail
 */
function buildEvidenceChain(auditTrail: AuditLogEntry[]): CourtReport["evidenceChain"] {
  const chain: CourtReport["evidenceChain"] = [];
  let step = 1;
  
  for (const entry of auditTrail) {
    // Document receipt
    chain.push({
      step: step++,
      action: "Document Received",
      timestamp: entry.timestamp,
      input: `File: ${entry.inputs.fileUrl || "N/A"}, Size: ${entry.inputs.fileSize || "N/A"} bytes`,
      output: "Document queued for processing",
      confidence: "N/A"
    });
    
    // Extraction
    chain.push({
      step: step++,
      action: "Text Extraction",
      timestamp: entry.timestamp,
      input: `Method: ${entry.extraction.method}`,
      output: `Extracted ${entry.extraction.textLength} characters from ${entry.extraction.pageCount || 1} page(s)`,
      confidence: entry.extraction.confidence
    });
    
    // Analysis prompts
    for (const prompt of entry.prompts) {
      chain.push({
        step: step++,
        action: `${prompt.category.charAt(0).toUpperCase() + prompt.category.slice(1)} Analysis`,
        timestamp: entry.timestamp,
        input: `Prompt version: ${prompt.promptVersion}, Hash: ${prompt.promptHash}`,
        output: "Analysis completed",
        confidence: "Model-dependent"
      });
    }
    
    // Final output
    chain.push({
      step: step++,
      action: "Report Generation",
      timestamp: entry.timestamp,
      input: `${entry.outputs.findingsCount} findings, ${entry.outputs.citationsCount} citations`,
      output: `Overall score: ${entry.outputs.overallScore}/100`,
      confidence: entry.outputs.warningsCount > 0 ? "With warnings" : "Standard"
    });
  }
  
  return chain;
}

/**
 * Generate client-friendly report
 */
export function generateClientReport(
  quoteId: number,
  sections: ReportSection[],
  overallScore: number,
  overallStatus: "green" | "amber" | "red",
  overallConfidence: "high" | "medium" | "low",
  recommendations: ClientReport["recommendations"],
  warnings: string[],
  projectAddress?: string,
  contractorName?: string
): ClientReport {
  // Validate all findings before generating report
  const allFindings = sections.flatMap(s => s.findings);
  const validation = citeOrBlockMiddleware.validateAll(allFindings);
  
  if (!validation.valid) {
    throw new Error(`Cannot generate report: ${validation.errors.join("; ")}`);
  }
  
  // Collect all citations
  const allCitations = sections.flatMap(s => s.citations);
  const standardsReferenced = Array.from(new Set(allCitations.map(c => `${c.authority} ${c.edition_or_version}`)));
  
  // Check for blocked language in summary
  const executiveSummary = generateExecutiveSummary(sections, overallScore, overallConfidence);
  const languageCheck = containsBlockedLanguage(executiveSummary);
  if (languageCheck.blocked) {
    throw new Error(`Report contains blocked language: ${languageCheck.terms.join(", ")}`);
  }
  
  return {
    reportId: `VALIDT-${quoteId}-${Date.now()}`,
    reportType: "client",
    generatedAt: new Date().toISOString(),
    quoteId,
    projectAddress,
    contractorName,
    overallScore,
    overallStatus,
    overallConfidence,
    executiveSummary,
    sections,
    recommendations,
    warnings: [
      ...warnings,
      ...validation.warnings
    ],
    disclaimer: STANDARD_DISCLAIMER,
    analysisVersion: "VALIDT v1.0",
    standardsReferenced
  };
}

/**
 * Generate court-defensible report
 */
export function generateCourtReport(
  quoteId: number,
  sections: ReportSection[],
  overallScore: number,
  overallStatus: "green" | "amber" | "red",
  overallConfidence: "high" | "medium" | "low",
  recommendations: ClientReport["recommendations"],
  warnings: string[],
  projectAddress?: string,
  contractorName?: string
): CourtReport {
  // Generate base client report first
  const clientReport = generateClientReport(
    quoteId,
    sections,
    overallScore,
    overallStatus,
    overallConfidence,
    recommendations,
    warnings,
    projectAddress,
    contractorName
  );
  
  // Get audit trail
  const auditTrail = getAuditTrail(quoteId);
  
  // Detect conflicting sources
  const allFindings = sections.flatMap(s => s.findings);
  const conflictingSources = citeOrBlockMiddleware.detectConflicts(allFindings);
  
  // Build evidence chain
  const evidenceChain = buildEvidenceChain(auditTrail);
  
  // Determine extraction method from audit trail
  const extractionMethod = auditTrail.length > 0 
    ? auditTrail[auditTrail.length - 1].extraction.method 
    : "unknown";
  
  return {
    ...clientReport,
    reportId: `VALIDT-COURT-${quoteId}-${Date.now()}`,
    reportType: "court",
    auditTrail,
    conflictingSources,
    evidenceChain,
    methodology: {
      extractionMethod: extractionMethod === "pdf-parse" 
        ? "PDF text extraction using pdf-parse library"
        : extractionMethod === "ocr"
        ? "Optical Character Recognition using Tesseract OCR"
        : "Hybrid extraction (PDF + OCR fallback)",
      analysisModel: "Perplexity Sonar Pro (2024-12)",
      standardsVersion: "NCC 2022, HB 39:2015, AS 1397:2021",
      validationSteps: [
        "Citation validation for all findings",
        "Blocked language screening",
        "Confidence scoring based on extraction quality",
        "Conflicting source detection"
      ]
    },
    legalNotices: [
      "This report is generated by automated systems and should not be relied upon as the sole basis for legal proceedings.",
      "All findings are assessments, not certifications or expert opinions.",
      "The accuracy of this report depends on the quality of the input document.",
      "Users should engage qualified expert witnesses for legal proceedings."
    ],
    expertWitnessStatement: EXPERT_WITNESS_STATEMENT
  };
}

/**
 * Convert findings to report section
 */
export function createReportSection(
  category: ReportSection["category"],
  title: string,
  findings: Finding[],
  score: number,
  confidence: "high" | "medium" | "low",
  assumptions: string[]
): ReportSection {
  // Collect all citations from findings
  const citations = findings.flatMap(f => f.citations);
  
  // Collect evidence required
  const evidenceRequired = findings
    .filter(f => f.evidence_required && f.evidence_required.length > 0)
    .flatMap(f => f.evidence_required || []);
  
  return {
    id: `section-${category}-${Date.now()}`,
    title,
    category,
    findings,
    score,
    confidence,
    assumptions,
    evidenceRequired: Array.from(new Set(evidenceRequired)),
    citations
  };
}

/**
 * Check if report can be exported
 */
export function canExportReport(report: ClientReport | CourtReport): {
  canExport: boolean;
  reason?: string;
  blockedSections: string[];
} {
  const blockedSections: string[] = [];
  
  for (const section of report.sections) {
    const validation = citeOrBlockMiddleware.validateAll(section.findings);
    if (!validation.valid) {
      blockedSections.push(section.id);
    }
  }
  
  if (blockedSections.length > 0) {
    return {
      canExport: false,
      reason: `${blockedSections.length} section(s) have validation errors`,
      blockedSections
    };
  }
  
  return { canExport: true, blockedSections: [] };
}

/**
 * Format report for PDF export
 */
export function formatReportForPDF(report: ClientReport | CourtReport): string {
  let markdown = `# VENTURR VALIDT ${report.reportType === "court" ? "Evidence Report" : "Verification Report"}\n\n`;
  markdown += `**Report ID:** ${report.reportId}\n`;
  markdown += `**Generated:** ${new Date(report.generatedAt).toLocaleString()}\n`;
  markdown += `**Quote ID:** ${report.quoteId}\n`;
  
  if (report.projectAddress) {
    markdown += `**Project Address:** ${report.projectAddress}\n`;
  }
  if (report.contractorName) {
    markdown += `**Contractor:** ${report.contractorName}\n`;
  }
  
  markdown += `\n---\n\n`;
  
  // Disclaimer at top for court reports
  if (report.reportType === "court") {
    markdown += `## Important Notice\n\n`;
    markdown += `> ${report.disclaimer.split('\n').join('\n> ')}\n\n`;
  }
  
  // Executive Summary
  markdown += `## Executive Summary\n\n`;
  markdown += `**Overall Score:** ${report.overallScore}/100 (${report.overallStatus.toUpperCase()})\n`;
  markdown += `**Confidence Level:** ${report.overallConfidence.toUpperCase()}\n\n`;
  markdown += `${report.executiveSummary}\n\n`;
  
  // Sections
  for (const section of report.sections) {
    markdown += `## ${section.title}\n\n`;
    markdown += `**Score:** ${section.score}/100 | **Confidence:** ${section.confidence}\n\n`;
    
    if (section.assumptions.length > 0) {
      markdown += `### Assumptions\n`;
      for (const assumption of section.assumptions) {
        markdown += `- ${assumption}\n`;
      }
      markdown += `\n`;
    }
    
    markdown += `### Findings\n\n`;
    markdown += `| Status | Finding | Message |\n`;
    markdown += `|--------|---------|----------|\n`;
    for (const finding of section.findings) {
      const statusIcon = finding.status === "assessed" ? "✓" : finding.status === "flagged" ? "⚠" : "?";
      markdown += `| ${statusIcon} ${finding.status} | ${finding.claim} | ${finding.message} |\n`;
    }
    markdown += `\n`;
    
    if (section.citations.length > 0) {
      markdown += `### References\n`;
      for (const citation of section.citations) {
        markdown += `- ${citation.authority}, ${citation.document}, ${citation.clause_or_page}\n`;
      }
      markdown += `\n`;
    }
    
    if (section.evidenceRequired.length > 0) {
      markdown += `### Evidence Still Required\n`;
      for (const evidence of section.evidenceRequired) {
        markdown += `- [ ] ${evidence}\n`;
      }
      markdown += `\n`;
    }
  }
  
  // Recommendations
  if (report.recommendations.length > 0) {
    markdown += `## Recommendations\n\n`;
    for (const rec of report.recommendations) {
      markdown += `### ${rec.priority.toUpperCase()}: ${rec.title}\n`;
      markdown += `${rec.description}\n\n`;
    }
  }
  
  // Court-specific sections
  if (report.reportType === "court") {
    const courtReport = report as CourtReport;
    
    markdown += `## Methodology\n\n`;
    markdown += `- **Extraction Method:** ${courtReport.methodology.extractionMethod}\n`;
    markdown += `- **Analysis Model:** ${courtReport.methodology.analysisModel}\n`;
    markdown += `- **Standards Version:** ${courtReport.methodology.standardsVersion}\n`;
    markdown += `- **Validation Steps:**\n`;
    for (const step of courtReport.methodology.validationSteps) {
      markdown += `  - ${step}\n`;
    }
    markdown += `\n`;
    
    if (courtReport.evidenceChain.length > 0) {
      markdown += `## Evidence Chain\n\n`;
      markdown += `| Step | Action | Timestamp | Input | Output | Confidence |\n`;
      markdown += `|------|--------|-----------|-------|--------|------------|\n`;
      for (const step of courtReport.evidenceChain) {
        markdown += `| ${step.step} | ${step.action} | ${step.timestamp} | ${step.input} | ${step.output} | ${step.confidence} |\n`;
      }
      markdown += `\n`;
    }
    
    if (courtReport.conflictingSources.length > 0) {
      markdown += `## Conflicting Sources Identified\n\n`;
      for (const conflict of courtReport.conflictingSources) {
        markdown += `- **${conflict.conflictType}:** ${conflict.description}\n`;
      }
      markdown += `\n`;
    }
    
    markdown += `## Expert Witness Statement\n\n`;
    markdown += `${courtReport.expertWitnessStatement}\n\n`;
    
    markdown += `## Legal Notices\n\n`;
    for (const notice of courtReport.legalNotices) {
      markdown += `- ${notice}\n`;
    }
    markdown += `\n`;
  }
  
  // Disclaimer at bottom
  markdown += `---\n\n`;
  markdown += `## Disclaimer\n\n`;
  markdown += report.disclaimer;
  
  return markdown;
}
