import { getDb } from "../server/db";
import { contractors } from "../drizzle/schema";

const australianContractors = [
  // NSW Contractors
  {
    name: "Sydney Elite Roofing",
    description: "Premium roofing services across Greater Sydney. Specializing in tile, metal, and flat roofing with 15+ years experience.",
    email: "contact@sydneyeliteroofing.com.au",
    phone: "+61 2 9876 5432",
    website: "https://www.sydneyeliteroofing.com.au",
    location: "Sydney, NSW",
    latitude: "-33.8688",
    longitude: "151.2093",
    rating: 4.8,
    reviewCount: 127,
    verified: true,
    verifiedAt: new Date("2024-01-15"),
    licenseNumber: "NSW-LIC-287456",
    insuranceExpiry: new Date("2025-12-31"),
  },
  {
    name: "Newcastle Kitchen Renovations",
    description: "Complete kitchen transformations with custom cabinetry and modern designs. Serving Newcastle and Hunter Region.",
    email: "info@newcastlekitchens.com.au",
    phone: "+61 2 4955 1234",
    website: "https://www.newcastlekitchens.com.au",
    location: "Newcastle, NSW",
    latitude: "-32.9283",
    longitude: "151.7817",
    rating: 4.6,
    reviewCount: 89,
    verified: true,
    verifiedAt: new Date("2024-02-20"),
    licenseNumber: "NSW-LIC-334521",
    insuranceExpiry: new Date("2025-11-30"),
  },
  {
    name: "Wollongong Deck Masters",
    description: "Expert deck construction using premium Australian hardwoods and composite materials. Licensed and insured.",
    email: "decks@wollongongdecks.com.au",
    phone: "+61 2 4228 7890",
    website: "https://www.wollongongdecks.com.au",
    location: "Wollongong, NSW",
    latitude: "-34.4278",
    longitude: "150.8931",
    rating: 4.7,
    reviewCount: 64,
    verified: true,
    verifiedAt: new Date("2024-03-10"),
    licenseNumber: "NSW-LIC-445632",
    insuranceExpiry: new Date("2026-01-31"),
  },
  {
    name: "Parramatta Bathroom Specialists",
    description: "Modern bathroom renovations with waterproofing expertise. Serving Western Sydney for over 10 years.",
    email: "hello@parramattabathrooms.com.au",
    phone: "+61 2 9630 4567",
    website: "https://www.parramattabathrooms.com.au",
    location: "Parramatta, NSW",
    latitude: "-33.8151",
    longitude: "151.0000",
    rating: 4.5,
    reviewCount: 103,
    verified: false,
    licenseNumber: "NSW-LIC-556743",
    insuranceExpiry: new Date("2025-10-31"),
  },
  {
    name: "Central Coast Concreting",
    description: "Driveways, pathways, and decorative concrete. Quality workmanship with 20+ years experience.",
    email: "info@centralcoastconcrete.com.au",
    phone: "+61 2 4385 2345",
    website: "https://www.centralcoastconcrete.com.au",
    location: "Gosford, NSW",
    latitude: "-33.4269",
    longitude: "151.3421",
    rating: 4.4,
    reviewCount: 78,
    verified: true,
    verifiedAt: new Date("2024-04-05"),
    licenseNumber: "NSW-LIC-667854",
    insuranceExpiry: new Date("2025-09-30"),
  },
  // VIC Contractors
  {
    name: "Melbourne Master Builders",
    description: "Full-service construction and renovation specialists. From concept to completion across metropolitan Melbourne.",
    email: "projects@melbournemasters.com.au",
    phone: "+61 3 9876 5432",
    website: "https://www.melbournemasters.com.au",
    location: "Melbourne, VIC",
    latitude: "-37.8136",
    longitude: "144.9631",
    rating: 4.9,
    reviewCount: 215,
    verified: true,
    verifiedAt: new Date("2023-11-20"),
    licenseNumber: "VIC-LIC-112233",
    insuranceExpiry: new Date("2026-03-31"),
  },
  {
    name: "Geelong Roofing Solutions",
    description: "Residential and commercial roofing. Colorbond specialists with storm damage expertise.",
    email: "contact@geelongroofing.com.au",
    phone: "+61 3 5221 8765",
    website: "https://www.geelongroofing.com.au",
    location: "Geelong, VIC",
    latitude: "-38.1499",
    longitude: "144.3617",
    rating: 4.7,
    reviewCount: 92,
    verified: true,
    verifiedAt: new Date("2024-01-25"),
    licenseNumber: "VIC-LIC-223344",
    insuranceExpiry: new Date("2025-12-31"),
  },
  {
    name: "Ballarat Kitchen & Bath",
    description: "Custom kitchens and bathrooms for regional Victoria. Award-winning designs with local craftsmanship.",
    email: "design@ballaratkitchens.com.au",
    phone: "+61 3 5331 4567",
    website: "https://www.ballaratkitchens.com.au",
    location: "Ballarat, VIC",
    latitude: "-37.5622",
    longitude: "143.8503",
    rating: 4.6,
    reviewCount: 67,
    verified: false,
    licenseNumber: "VIC-LIC-334455",
    insuranceExpiry: new Date("2025-11-30"),
  },
  {
    name: "Frankston Fencing Co",
    description: "Timber, Colorbond, and pool fencing. Compliant with all Victorian building standards.",
    email: "info@frankstonfen cing.com.au",
    phone: "+61 3 9783 2345",
    website: "https://www.frankstonfen cing.com.au",
    location: "Frankston, VIC",
    latitude: "-38.1421",
    longitude: "145.1237",
    rating: 4.5,
    reviewCount: 81,
    verified: true,
    verifiedAt: new Date("2024-02-15"),
    licenseNumber: "VIC-LIC-445566",
    insuranceExpiry: new Date("2026-02-28"),
  },
  {
    name: "Dandenong HVAC Experts",
    description: "Heating, cooling, and ventilation installation. Daikin and Mitsubishi certified technicians.",
    email: "service@dandenonghvac.com.au",
    phone: "+61 3 9791 6789",
    website: "https://www.dandenonghvac.com.au",
    location: "Dandenong, VIC",
    latitude: "-37.9871",
    longitude: "145.2154",
    rating: 4.8,
    reviewCount: 134,
    verified: true,
    verifiedAt: new Date("2024-03-20"),
    licenseNumber: "VIC-LIC-556677",
    insuranceExpiry: new Date("2025-10-31"),
  },
  // QLD Contractors
  {
    name: "Brisbane Premier Roofing",
    description: "Tropical roofing specialists. Cyclone-rated installations and repairs across Brisbane and Moreton Bay.",
    email: "info@brisbanepremierroofing.com.au",
    phone: "+61 7 3876 5432",
    website: "https://www.brisbanepremierroofing.com.au",
    location: "Brisbane, QLD",
    latitude: "-27.4698",
    longitude: "153.0251",
    rating: 4.7,
    reviewCount: 156,
    verified: true,
    verifiedAt: new Date("2024-01-10"),
    licenseNumber: "QLD-LIC-778899",
    insuranceExpiry: new Date("2026-04-30"),
  },
  {
    name: "Gold Coast Deck Builders",
    description: "Luxury outdoor living spaces. Decks, pergolas, and alfresco areas designed for Queensland lifestyle.",
    email: "decks@goldcoastdecks.com.au",
    phone: "+61 7 5532 8765",
    website: "https://www.goldcoastdecks.com.au",
    location: "Gold Coast, QLD",
    latitude: "-28.0167",
    longitude: "153.4000",
    rating: 4.9,
    reviewCount: 187,
    verified: true,
    verifiedAt: new Date("2023-12-15"),
    licenseNumber: "QLD-LIC-889900",
    insuranceExpiry: new Date("2025-12-31"),
  },
  {
    name: "Sunshine Coast Solar Solutions",
    description: "Residential and commercial solar installations. CEC accredited with 10-year workmanship warranty.",
    email: "solar@sunshinecoastsolar.com.au",
    phone: "+61 7 5443 2345",
    website: "https://www.sunshinecoastsolar.com.au",
    location: "Maroochydore, QLD",
    latitude: "-26.6569",
    longitude: "153.0903",
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    verifiedAt: new Date("2024-02-28"),
    licenseNumber: "QLD-LIC-990011",
    insuranceExpiry: new Date("2026-01-31"),
  },
  {
    name: "Townsville Painting Pros",
    description: "Interior and exterior painting for North Queensland. Heat-resistant coatings and color consulting.",
    email: "paint@townsvillepainting.com.au",
    phone: "+61 7 4721 4567",
    website: "https://www.townsvillepainting.com.au",
    location: "Townsville, QLD",
    latitude: "-19.2590",
    longitude: "146.8169",
    rating: 4.6,
    reviewCount: 73,
    verified: false,
    licenseNumber: "QLD-LIC-101112",
    insuranceExpiry: new Date("2025-11-30"),
  },
  {
    name: "Cairns Tropical Landscaping",
    description: "Garden design and construction for tropical climates. Irrigation, retaining walls, and native plantings.",
    email: "gardens@cairnslandscaping.com.au",
    phone: "+61 7 4031 6789",
    website: "https://www.cairnslandscaping.com.au",
    location: "Cairns, QLD",
    latitude: "-16.9186",
    longitude: "145.7781",
    rating: 4.7,
    reviewCount: 95,
    verified: true,
    verifiedAt: new Date("2024-03-15"),
    licenseNumber: "QLD-LIC-121314",
    insuranceExpiry: new Date("2025-10-31"),
  },
  // WA Contractors
  {
    name: "Perth Prestige Builders",
    description: "Luxury home renovations and extensions. Serving Perth metro and surrounding suburbs for 18 years.",
    email: "build@perthprestige.com.au",
    phone: "+61 8 9321 5432",
    website: "https://www.perthprestige.com.au",
    location: "Perth, WA",
    latitude: "-31.9505",
    longitude: "115.8605",
    rating: 4.8,
    reviewCount: 168,
    verified: true,
    verifiedAt: new Date("2024-01-20"),
    licenseNumber: "WA-LIC-131415",
    insuranceExpiry: new Date("2026-03-31"),
  },
  {
    name: "Fremantle Roofing & Gutters",
    description: "Roof restoration, repairs, and gutter replacement. Specializing in heritage properties.",
    email: "info@fremantleroofing.com.au",
    phone: "+61 8 9335 8765",
    website: "https://www.fremantleroofing.com.au",
    location: "Fremantle, WA",
    latitude: "-32.0569",
    longitude: "115.7439",
    rating: 4.6,
    reviewCount: 84,
    verified: true,
    verifiedAt: new Date("2024-02-10"),
    licenseNumber: "WA-LIC-141516",
    insuranceExpiry: new Date("2025-12-31"),
  },
  {
    name: "Joondalup Kitchen Designs",
    description: "Contemporary kitchen renovations with European appliances. Showroom open 6 days.",
    email: "design@joondalupkitchens.com.au",
    phone: "+61 8 9301 2345",
    website: "https://www.joondalupkitchens.com.au",
    location: "Joondalup, WA",
    latitude: "-31.7448",
    longitude: "115.7661",
    rating: 4.7,
    reviewCount: 91,
    verified: false,
    licenseNumber: "WA-LIC-151617",
    insuranceExpiry: new Date("2025-11-30"),
  },
  {
    name: "Mandurah Pool & Spa",
    description: "Inground pool construction and spa installations. Fibreglass and concrete specialists.",
    email: "pools@mandurahpools.com.au",
    phone: "+61 8 9535 4567",
    website: "https://www.mandurahpools.com.au",
    location: "Mandurah, WA",
    latitude: "-32.5269",
    longitude: "115.7231",
    rating: 4.5,
    reviewCount: 77,
    verified: true,
    verifiedAt: new Date("2024-03-25"),
    licenseNumber: "WA-LIC-161718",
    insuranceExpiry: new Date("2026-02-28"),
  },
  {
    name: "Bunbury Electrical Services",
    description: "Licensed electricians for South West WA. Residential, commercial, and solar installations.",
    email: "sparky@bunburyelectrical.com.au",
    phone: "+61 8 9721 6789",
    website: "https://www.bunburyelectrical.com.au",
    location: "Bunbury, WA",
    latitude: "-33.3267",
    longitude: "115.6397",
    rating: 4.8,
    reviewCount: 119,
    verified: true,
    verifiedAt: new Date("2024-04-01"),
    licenseNumber: "WA-LIC-171819",
    insuranceExpiry: new Date("2025-10-31"),
  },
  // SA Contractors
  {
    name: "Adelaide Quality Roofing",
    description: "Roof replacement and repairs for Adelaide metro. Tile, metal, and Colorbond specialists.",
    email: "roofs@adelaidequality.com.au",
    phone: "+61 8 8234 5432",
    website: "https://www.adelaidequality.com.au",
    location: "Adelaide, SA",
    latitude: "-34.9285",
    longitude: "138.6007",
    rating: 4.7,
    reviewCount: 132,
    verified: true,
    verifiedAt: new Date("2024-01-30"),
    licenseNumber: "SA-LIC-181920",
    insuranceExpiry: new Date("2026-04-30"),
  },
  {
    name: "Glenelg Bathroom Renovations",
    description: "Complete bathroom makeovers with modern fixtures. Waterproofing and tiling experts.",
    email: "bathrooms@glenelgrenovations.com.au",
    phone: "+61 8 8295 8765",
    website: "https://www.glenelgrenovations.com.au",
    location: "Glenelg, SA",
    latitude: "-34.9799",
    longitude: "138.5127",
    rating: 4.6,
    reviewCount: 87,
    verified: false,
    licenseNumber: "SA-LIC-192021",
    insuranceExpiry: new Date("2025-12-31"),
  },
  {
    name: "Port Adelaide Concreting",
    description: "Driveways, shed slabs, and decorative concrete. Serving northern suburbs for 15 years.",
    email: "concrete@portadelaideconcrete.com.au",
    phone: "+61 8 8447 2345",
    website: "https://www.portadelaideconcrete.com.au",
    location: "Port Adelaide, SA",
    latitude: "-34.8476",
    longitude: "138.5041",
    rating: 4.5,
    reviewCount: 69,
    verified: true,
    verifiedAt: new Date("2024-02-20"),
    licenseNumber: "SA-LIC-202122",
    insuranceExpiry: new Date("2025-11-30"),
  },
  {
    name: "McLaren Vale Landscaping",
    description: "Garden design and construction for Adelaide Hills and Fleurieu Peninsula. Sustainable practices.",
    email: "gardens@mclarenvalelandscaping.com.au",
    phone: "+61 8 8323 4567",
    website: "https://www.mclarenvalelandscaping.com.au",
    location: "McLaren Vale, SA",
    latitude: "-35.2167",
    longitude: "138.5333",
    rating: 4.7,
    reviewCount: 94,
    verified: true,
    verifiedAt: new Date("2024-03-10"),
    licenseNumber: "SA-LIC-212223",
    insuranceExpiry: new Date("2026-01-31"),
  },
  {
    name: "Mount Barker Home Extensions",
    description: "Second story additions and ground floor extensions. Architectural design and construction.",
    email: "extensions@mountbarkerbuilders.com.au",
    phone: "+61 8 8391 6789",
    website: "https://www.mountbarkerbuilders.com.au",
    location: "Mount Barker, SA",
    latitude: "-35.0686",
    longitude: "138.8627",
    rating: 4.8,
    reviewCount: 106,
    verified: true,
    verifiedAt: new Date("2024-04-05"),
    licenseNumber: "SA-LIC-222324",
    insuranceExpiry: new Date("2025-10-31"),
  },
];

async function seedContractors() {
  console.log("Starting contractor seeding...");
  
  const db = await getDb();
  if (!db) {
    throw new Error("Database not available");
  }

  try {
    // Insert all contractors
    for (const contractor of australianContractors) {
      await db.insert(contractors).values(contractor);
      console.log(`✓ Seeded: ${contractor.name}`);
    }

    console.log(`\n✅ Successfully seeded ${australianContractors.length} contractors!`);
    console.log("\nBreakdown by state:");
    console.log("- NSW: 5 contractors");
    console.log("- VIC: 5 contractors");
    console.log("- QLD: 5 contractors");
    console.log("- WA: 5 contractors");
    console.log("- SA: 5 contractors");
    console.log("\nVerified contractors: " + australianContractors.filter(c => c.verified).length);
    console.log("Average rating: " + (australianContractors.reduce((sum, c) => sum + c.rating, 0) / australianContractors.length).toFixed(2));
    
    process.exit(0);
  } catch (error) {
    console.error("Error seeding contractors:", error);
    process.exit(1);
  }
}

seedContractors();
