import { AlertTriangle, Info, ExternalLink } from "lucide-react";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface DisclaimerProps {
  variant?: "banner" | "inline" | "compact";
  showLearnMore?: boolean;
}

export function Disclaimer({ variant = "banner", showLearnMore = true }: DisclaimerProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  if (variant === "compact") {
    return (
      <div className="flex items-start gap-2 p-3 rounded-lg bg-muted/50 border border-border/50 text-xs text-muted-foreground">
        <Info className="w-4 h-4 mt-0.5 flex-shrink-0" />
        <p>
          This analysis is AI-generated and for informational purposes only. 
          Not professional advice.{" "}
          <button 
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-primary hover:underline"
          >
            {isExpanded ? "Show less" : "Learn more"}
          </button>
        </p>
      </div>
    );
  }

  if (variant === "inline") {
    return (
      <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/20">
        <div className="flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
          <div className="space-y-2">
            <p className="text-sm font-medium text-foreground">Important Notice</p>
            <p className="text-sm text-muted-foreground">
              This analysis is generated by artificial intelligence and is provided for 
              <strong className="text-foreground"> informational purposes only</strong>. 
              It does not constitute legal, financial, engineering, or professional advice.
            </p>
            {showLearnMore && (
              <button 
                onClick={() => setIsExpanded(!isExpanded)}
                className="text-sm text-primary hover:underline flex items-center gap-1"
              >
                {isExpanded ? "Show less" : "View full disclaimer"}
              </button>
            )}
            <AnimatePresence>
              {isExpanded && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="overflow-hidden"
                >
                  <div className="pt-3 space-y-2 text-sm text-muted-foreground border-t border-amber-500/20 mt-3">
                    <p>
                      <strong className="text-foreground">VALIDT does not verify or attest to compliance</strong> with any 
                      building code, standard, or regulation. Scores and assessments are estimates based on 
                      available information and may not reflect actual quote quality or market conditions.
                    </p>
                    <p>
                      Users should engage qualified professionals (licensed builders, engineers, or legal 
                      advisors) for compliance verification and professional advice before making decisions.
                    </p>
                    <p>
                      VENTURR accepts no liability for decisions made based on this analysis. Market rates 
                      and compliance requirements vary by location, project scope, and time.
                    </p>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>
    );
  }

  // Banner variant (default)
  return (
    <div className="bg-gradient-to-r from-amber-500/10 via-amber-500/5 to-transparent border-l-4 border-amber-500 p-4 md:p-6 rounded-r-lg">
      <div className="flex items-start gap-4">
        <div className="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center flex-shrink-0">
          <AlertTriangle className="w-5 h-5 text-amber-500" />
        </div>
        <div className="flex-1 space-y-3">
          <div>
            <h4 className="font-semibold text-foreground">Important Disclaimer</h4>
            <p className="text-sm text-muted-foreground mt-1">
              This analysis is generated by artificial intelligence and is provided for 
              <strong className="text-foreground"> informational purposes only</strong>.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 gap-3 text-sm">
            <div className="flex items-start gap-2">
              <span className="text-amber-500 font-bold">✕</span>
              <span className="text-muted-foreground">Not legal or financial advice</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-amber-500 font-bold">✕</span>
              <span className="text-muted-foreground">Not engineering certification</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-amber-500 font-bold">✕</span>
              <span className="text-muted-foreground">Not compliance verification</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-amber-500 font-bold">✕</span>
              <span className="text-muted-foreground">Not an assurance of accuracy</span>
            </div>
          </div>

          <p className="text-sm text-muted-foreground">
            Scores are estimates based on available data. Consult qualified professionals 
            (licensed builders, engineers, or legal advisors) before making decisions.
          </p>

          {showLearnMore && (
            <button 
              onClick={() => setIsExpanded(!isExpanded)}
              className="text-sm text-primary hover:underline flex items-center gap-1"
            >
              {isExpanded ? "Hide details" : "View full disclaimer"}
              <ExternalLink className="w-3 h-3" />
            </button>
          )}

          <AnimatePresence>
            {isExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: "auto", opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                <div className="pt-4 space-y-3 text-sm text-muted-foreground border-t border-amber-500/20">
                  <p>
                    <strong className="text-foreground">Limitation of Liability:</strong> VENTURR VALDT 
                    provides this analysis as a tool to assist in evaluating construction quotes. We do 
                    not warrant the accuracy, completeness, or reliability of any information provided.
                  </p>
                  <p>
                    <strong className="text-foreground">No Professional Relationship:</strong> Use of 
                    this service does not create a professional relationship between you and VENTURR. 
                    This analysis should not be relied upon as a substitute for professional advice.
                  </p>
                  <p>
                    <strong className="text-foreground">Market Data Limitations:</strong> Pricing 
                    comparisons are based on historical data and estimates. Actual market rates vary 
                    by location, project specifics, material availability, and other factors.
                  </p>
                  <p>
                    <strong className="text-foreground">Compliance Note:</strong> References to building 
                    codes (HB-39, NCC, AS/NZS standards) are for informational purposes. Only qualified 
                    professionals can verify compliance with building regulations.
                  </p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}

export function ReportDisclaimer() {
  return (
    <div className="mt-8 pt-6 border-t border-border/50">
      <Disclaimer variant="banner" showLearnMore={true} />
    </div>
  );
}

export function InlineDisclaimer() {
  return <Disclaimer variant="inline" showLearnMore={true} />;
}

export function CompactDisclaimer() {
  return <Disclaimer variant="compact" showLearnMore={false} />;
}
